parse ("(a)")
    # parse ("((a))")
    # parse ("a+a")
    # parse ("a*a")
    # parse ("((a)/(a)-(a))")
    # parse ("((a)/(a)-(a))*((a)/(a)-(a))")
    # parse ("a+a*a-a/a")
    # parse ("a/a-a*a+a")
    # parse ("(a+a*a-a/a)")
    # parse ("(a/a-a*a+a)")
    # parse ("(a+(a*a*a)+a+a)")
    # parse ("(a*(a+a+a)*a*a)")